version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
    volumes:
      - static_data:/backend/staticfiles
      - media_file:/backend/mediafiles
    env_file: # if .env in root, we have to show .env here must
      - ./.env

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/backend/staticfiles
      - media_file:/backend/mediafiles
    ports:
      - "80:80"
      # - "8000:8000"
    env_file: # if .env in root, we have to show .env here must
      - ./.env
    depends_on:
      - backend
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
volumes:
  static_data:
  media_file:
