# Generated by Django 2.2.20 on 2021-04-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('spoonApi', models.CharField(blank=True, max_length=255, null=True)),
                ('spoonHash', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightLbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('weightKgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dailyProteinPerKg', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dailyCarbPerKg', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dailyFatPerKg', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dailyProteinNeed', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dailyCarbsNeed', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('dailyFatNeed', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
