# Generated by Django 2.2.20 on 2021-04-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intensity', models.CharField(choices=[('Rest', 'Rest'), ('Easy', 'Easy'), ('Workout', 'Workout'), ('All Out', 'All Out')], max_length=255)),
                ('busyDay', models.BooleanField(default=False)),
                ('needBreakfast', models.BooleanField(default=True)),
                ('needAmSnack', models.BooleanField(default=True)),
                ('needLunch', models.BooleanField(default=True)),
                ('needPmSnack', models.BooleanField(default=True)),
                ('needDinner', models.BooleanField(default=True)),
                ('repeatMeals', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('tags', models.TextField(max_length=1000)),
                ('title', models.TextField(max_length=1000)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255)),
                ('ingredients', models.TextField(max_length=2500, null=True)),
                ('directions', models.TextField(max_length=2500, null=True)),
                ('highProtein', models.BooleanField(default=False)),
                ('highCarbs', models.BooleanField(default=False)),
                ('highFat', models.BooleanField(default=False)),
                ('highCalories', models.BooleanField(default=False)),
                ('lowCarbs', models.BooleanField(default=False)),
                ('percentCarbs', models.FloatField(null=True)),
                ('percentProtein', models.FloatField(null=True)),
                ('percentFat', models.FloatField(null=True)),
                ('percentCalories', models.FloatField(null=True)),
                ('mealTypes', models.CharField(max_length=255, null=True)),
                ('cookingMins', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('Favorite', 'Favorite'), ('Not Interested', 'Not Interested'), ('Made It', 'Made It'), ('Loved It', 'Love It')], max_length=255, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeOverview')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('test', models.BooleanField(blank=True, default=False)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('shoppingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ShoppingList')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeOverview'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('mealPosition', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening snack', 'Evening Snack')], max_length=255, null=True)),
                ('notMade', models.BooleanField(default=False)),
                ('likedIt', models.BooleanField(default=False)),
                ('notLiked', models.BooleanField(default=False)),
                ('feedbackGiven', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('dayIntensity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.DayIntensity')),
                ('mealChosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeOverview')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeOverview')),
            ],
        ),
    ]
