name: Build and Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy django app
        uses: appleboy/ssh-action@master

        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /home/fuel-app/
            git clone git@github.com:lkstrategy/fuel-app.git
            docker-compose up
            echo 'Deployment Done'
